GET http://localhost:8080/participants/
Accept: application/json

<> 2026-04-25T110337.200.json
<> 2026-04-25T110335.200.json
<> 2026-04-25T105720.200.json

###
GET http://localhost:8080/participants/user2
Accept: application/json

<> 2026-04-25T110338.200.json
<> 2026-04-25T110335-1.200.json

###
GET http://localhost:8080/participants/user1231
Accept: application/json

###
POST http://localhost:8080/participants
Content-Type: application/json

{
  "login": "somelogin",
  "password": "some password"
}

<> 2026-04-25T110338.409.txt
<> 2026-04-25T110335.409.txt
<> 2026-04-25T105720.409.txt

###
POST http://localhost:8080/participants
Content-Type: application/json

{
  "login": "somelogin",
  "password": "some password"
}

<> 2026-04-25T110338-1.409.txt
<> 2026-04-25T110335-1.409.txt
<> 2026-04-25T105720-1.409.txt

###
POST http://localhost:8080/participants
Content-Type: application/json

{
  "login": "somelogin2",
  "password": "some password"
}

<> 2026-04-25T110338-2.409.txt
<> 2026-04-25T110335-2.409.txt
<> 2026-04-25T105720-2.409.txt

###
DELETE http://localhost:8080/participants
Content-Type: application/json

{
  "login": "somelogin2",
  "password": "some password"
}

<> 2026-04-25T110338.405.json
<> 2026-04-25T110335.405.json
<> 2026-04-25T105720.405.json

###
PUT http://localhost:8080/participants
Content-Type: application/json

{
  "login": "somelogin",
  "password": "new pswd"
}

###
GET http://localhost:8080/participants
Accept: application/json

<> 2026-04-25T110338-1.200.json
<> 2026-04-25T110335-2.200.json
<> 2026-04-25T105720-2.200.json

###
GET http://localhost:8080/participants?sortBy=login&sortOrder=DESC
Accept: application/json

###
GET http://localhost:8080/participants?sortBy=login&sortOrder=ASC
Accept: application/json

###
GET http://localhost:8080/participants?sortBy=login
Accept: application/json

###
GET http://localhost:8080/participants?sortBy=logwn
Accept: application/json

###
GET http://localhost:8080/participants?sortBy=login&sortOrder=ASCawd
Accept: application/json

###
GET http://localhost:8080/participants?key=some
Accept: application/json

###
GET http://localhost:8080/participants?key=us
Accept: application/json

###
GET http://localhost:8080/participants?key=some123123
Accept: application/json
